import { NextPage } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import ListView from "../components/List/ListView";
import apiKit from "../utils/ApiKit";
import { useList } from "../utils/context/ListContext";

const HomePage: NextPage<{}> = () => {

  const list = useList()

  useEffect(() =>{
    apiKit.getRecipies().then(response => {
      list.setRecipies(response.data || [])
    }).catch((error) => {
      console.warn(`ERROR: GETTING RECIPIE LIST ${error}`);
    })
  },[])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListView/>
    </div>
  );
};

export default HomePage;
