import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import ListView from "../components/List/ListView";

const HomePage: NextPage<{}> = () => {

  return (
    <div>
      <Head>
        <title>Scoutrecpt kalkylator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/scout.ico" />
      </Head>
      <ListView/>
    </div>
  );
};

export default HomePage;
